# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html
# The name of this app. Must be unique within a project.
name: app
# The runtime the application uses.
type: 'java:8'
disk: 1024
source:
     root: /

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: mvn clean install

mounts:
    'server/':
        source: local
        source_path: server_source

web:
    commands:
        start: |
            cp target/dependency/webapp-runner.jar server/webapp-runner.jar
            cp target/tomcat.war server/tomcat.war
            cd server && java -jar -Xmx$(jq .info.limits.memory /run/config.json)m -XX:+ExitOnOutOfMemoryError webapp-runner.jar --port $PORT tomcat.war
name: app
type: 'java:8'
disk: 1024
source:
     root: /
hooks:
    build: mvn clean install
mounts:
    'server/':
        source: local
        source_path: server_source
web:
    commands:
        start: |
            cp target/dependency/webapp-runner.jar server/webapp-runner.jar
            cp target/tomcat.war server/tomcat.war
            cd server && java -jar -Xmx$(jq .info.limits.memory /run/config.json)m -XX:+ExitOnOutOfMemoryError webapp-runner.jar --port $PORT tomcat.war
