-   name: api
    type: golang:1.14
    source:
        root: apiapp
    hooks:
        build: |
            go build -o bin/app
    web:
        upstream:
            socket_family: tcp
            protocol: http
        commands:
            start: ./bin/app
        locations:
            /:
                allow: false
                passthru: true

-   name: main
    type: "php:7.4"
    source:
        root: mainapp
    web:
        locations:
            "/":
                root: "web"
                passthru: "/index.php"

-   name: admin
    type: "php:7.4"
    size: S
    source:
        root: mainapp
    web:
        locations:
            "/":
                root: "web"
                passthru: "/admin.php"
